server:
  port: 8080

spring:
  application:
    name: library

  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: Abdualim123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

application:
  security:
    jwt:
      secret-key: 8f7c8a2b9d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a
      expiration: 86400000

file:
  upload-dir: ./uploads/covers